### ISSUE TITLE
Weekly Newsletter via Email bugs

### ISSUE THREAD

**Issue by Elaniobro** [Elaniobro/newyorkmyc-ui#17]
### Description ✍️:

There are a bunch of bugs in the weekly email that needs to be fixed:

### ToDo: ✅
- [ ] iNaturalist link should point to [iNat](newyorkmyc.org/resources/faq/walks/)
- [ ] Walks link should point to [walks](newyorkmyc.org/resources/faq/walks/)
- [ ] email should be `president@newyorkmyc.org`
- [ ] copyright should be `2022`
- [ ] url should read `https://newyorkmyc.org`

### Visual 🔍
<img width="316" alt="Screen Shot 2022-02-10 at 10 11 41" src="https://user-images.githubusercontent.com/710847/153437823-3544f4b0-5446-4b6a-aeb2-78ee5736877e.png">

**Comment by Elaniobro** [comment]
@sigridjakob, what is the status of this work? Thanks!
